// Main client
export { Modulex } from './client';

// Configuration
export type { ModulexConfig } from './config';

// Errors
export {
  ModulexError,
  BadRequestError,
  AuthenticationError,
  PermissionError,
  NotFoundError,
  ConflictError,
  ValidationError,
  RateLimitError,
  InternalError,
  ExternalServiceError,
  ServiceUnavailableError,
  StreamError,
  TimeoutError,
} from './errors';

// SSE streaming
export type { SSEEvent } from './streaming';

// All types
export type {
  // Shared
  RequestOptions,
  SuccessResponse,
  PaginatedList,

  // Auth
  UserResponse,
  OrganizationInfo,
  OrganizationsResponse,
  InvitationsResponse,
  InvitationResponse,
  InvitationObject,
  InvitationOrganization,
  InvitationInviter,
  AcceptedInvitationOrganization,
  LeaveResponse,

  // API Keys
  CreateApiKeyParams,
  ApiKeyResponse,
  CreateApiKeyResponse,
  ApiKeyListResponse,
  RevokeApiKeyResponse,

  // Organizations
  CreateOrganizationParams,
  CreateOrganizationResponse,
  LLMsResponse,
  InviteParams,
  CancelInvitationResponse,
  RoleUpdateParams,
  RoleUpdateResponse,
  InvitePreviewResponse,
  LLMModelEntry,
  ComposerLLMSelection,
  SettingsResponse,
  SetModelVisibilityParams,
  SetModelVisibilityResponse,
  ComposerLLMParams,
  ComposerLLMResponse,

  // Workflows
  WorkflowMetadata,
  WorkflowConfig,
  StateSchemaField,
  StateSchema,
  NodeType,
  LLMConfig,
  ToolDefinition,
  RetryConfig,
  LLMNodeConfig,
  ToolNodeConfig,
  AgentNodeConfig,
  FunctionNodeConfig,
  ConditionalBranch,
  LoopConfig,
  ConditionalNodeConfig,
  InterruptNodeConfig,
  TransformerOperation,
  TransformerNodeConfig,
  GuardrailsNodeConfig,
  KnowledgeNodeConfig,
  NodeDefinition,
  EdgeDefinition,
  WorkflowDefinition,
  CreateWorkflowParams,
  UpdateWorkflowParams,
  WorkflowSummary,
  WorkflowResponse,
  WorkflowListParams,
  WorkflowListResponse,
  DeleteWorkflowResponse,
  BuilderDetailsParams,
  BuilderDetailsResponse,
  BuilderNodeTypeDescriptor,
  WorkflowChangeEvent,

  // Executions
  WorkflowRunParams,
  WorkflowMessageEnvelope,
  WorkflowRunResponse,
  WorkflowStateResponse,
  WorkflowResumeParams,
  WorkflowResumeResponse,
  CancelResponse,
  MetadataEventData,
  NodeStartedEventData,
  NodeUpdateEventData,
  InterruptEventData,
  ResumedEventData,
  DoneEventData,
  ErrorEventData,
  WorkflowSSEEvent,

  // Workflow Runs (durable history)
  WorkflowRunListParams,
  WorkflowRunListItem,
  WorkflowRunListResponse,
  WorkflowRunDetail,

  // Deployments
  CreateDeploymentParams,
  DeploymentResponse,
  DeploymentListParams,
  DeploymentListResponse,
  DeploymentDetailResponse,
  ActivateDeploymentResponse,
  DeactivateDeploymentResponse,
  DeleteDeploymentResponse,

  // Chats
  ChatResponse,
  ChatMessageResponse,
  ChatMessagesParams,
  ChatMessagesResponse,
  UpdateChatParams,
  ChatListResponse,
  ChatListItem,
  ChatConnectedEvent,
  ChatListUpdatedEvent,

  // Credentials
  CredentialResponse,
  CreateCredentialParams,
  UpdateCredentialParams,
  CredentialListGrouped,
  CredentialListFlat,
  CredentialListParams,
  TestTemporaryParams,
  TestTemporaryResponse,
  TestCredentialResponse,
  CredentialUsageParams,
  CredentialUsageResponse,
  CredentialAuditParams,
  CredentialDetailResponse,
  AuditLogResponse,
  MCPServerCredentialResponse,
  InitiateOAuth2Params,
  OAuth2InitiateResponse,
  ModulexKeyIntegrationStatus,
  ModulexKeyBulkSummary,
  ModulexKeyBulkEventData,
  McpServerParams,
  McpToolsResponse,
  RefreshDiscoveryResponse,

  // Integrations
  BrowseParams,
  BrowseResponse,
  IntegrationResponse,
  ToolIntegrationResponse,
  LLMProviderResponse,
  KnowledgeProviderResponse,
  IntegrationMetadata,
  IntegrationDetail,
  AuthSchema,

  // Knowledge
  EmbeddingConfig,
  ChunkingConfig,
  CreateKnowledgeBaseParams,
  UpdateKnowledgeBaseParams,
  KnowledgeBaseResponse,
  KnowledgeBaseListParams,
  KnowledgeBaseStatsResponse,
  DocumentResponse,
  DocumentListParams,
  UploadDocumentParams,
  DocumentStatusResponse,
  ChunkResponse,
  DocumentChunksParams,
  DocumentChunksResponse,
  SearchParams,
  SearchResponse,
  SearchMatch,
  MultiSearchParams,
  HybridSearchParams,
  RetrieveContextParams,
  RetrieveContextResponse,
  SupportedFileTypesResponse,

  // Schedules
  CreateScheduleParams,
  UpdateScheduleParams,
  ScheduleResponse,
  ScheduleListParams,
  ScheduleListResponse,
  ScheduleRunResponse,
  ScheduleRunListParams,
  ScheduleRunListResponse,
  ScheduleRunStatsParams,
  ScheduleRunStatsResponse,
  RetryRunResponse,
  DeleteScheduleResponse,

  // HITL (Human-in-the-Loop) — shared by Composer & Assistant
  ChoiceOption,
  CredentialAuthOption,
  UserInputRequestBase,
  SingleChoiceRequest,
  MultiChoiceRequest,
  YesNoRequest,
  FreeTextRequest,
  CredentialRequest,
  UserInputRequest,
  SingleChoiceResponse,
  MultiChoiceResponse,
  YesNoResponse,
  FreeTextResponse,
  CredentialAddedResponse,
  CredentialFailureCode,
  CredentialFailedResponse,
  SkippedResponse,
  UserInputResponse,

  // Composer
  ComposerChatParams,
  ComposerChatResponse,
  ComposerMessageResponse,
  ComposerChatDetailResponse,
  ComposerStatusResponse,
  ComposerWorkflowSync,
  ComposerSaveParams,
  ComposerSaveResponse,
  ComposerRevertResponse,
  ComposerResumeParams,
  ComposerResumeResponse,
  ComposerFocusParams,
  ComposerFocusResponse,
  ComposerListParams,
  ComposerChatListItem,
  ComposerChatListResponse,
  ComposerSSEEvent,
  ComposerDeleteParams,
  ComposerDeleteResponse,
  ComposerCancelResponse,

  // Assistant
  AssistantChatParams,
  AssistantChatResponse,
  AssistantMessageResponse,
  AssistantChatDetailResponse,
  AssistantStatusResponse,
  AssistantResumeParams,
  AssistantResumeResponse,
  AssistantListParams,
  AssistantChatSummary,
  AssistantChatListResponse,
  AssistantDeleteParams,
  AssistantDeleteResponse,
  AssistantCancelResponse,
  AssistantSSEEvent,

  // Dashboard
  DashboardLogsParams,
  DashboardLogsResponse,
  AnalyticsOverviewParams,
  AnalyticsOverviewResponse,
  AnalyticsToolsParams,
  AnalyticsToolsResponse,
  AnalyticsLLMUsageResponse,
  DashboardUsersParams,
  DashboardUsersResponse,
  DashboardErrorEnvelope,
  CurrentMonthCreditUsage,
  DashboardLogsFilters,
  DashboardLogsSuccess,
  AnalyticsSubscription,
  OverviewCredentialUsageLog,
  AnalyticsOverview,
  AnalyticsOverviewSuccess,
  MostUsedAction,
  ToolUsage,
  AnalyticsToolsData,
  AnalyticsToolsSuccess,
  AnalyticsLLMUsageParams,
  LLMUsage,
  AnalyticsLLMUsageData,
  AnalyticsLLMUsageSuccess,
  DashboardMemberUser,
  DashboardInvitationUser,
  DashboardUser,
  DashboardUsersSuccess,

  // System (timezones)
  TimezoneOption,
  TimezoneGroup,
  TimezoneListResponse,

  // Notifications
  NotificationResponse,
  NotificationListResponse,
  CreateNotificationParams,
  OrganizationNotificationTopic,
  SystemNotificationTopic,
  NotificationBase,
  InvitationNotification,
  SystemNotification,
  OrganizationNotification,
  CreatedNotification,
  CreateNotificationResponse,
} from './types';
